language: python
python:
  - "3.2"
  - "3.3"
script: ./test-ci
env:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit
before_install:
    - sudo add-apt-repository -y ppa:neomantra/luajit-v2.1
    - sudo apt-get update -qq
    - sudo apt-get install cgroup-tools $LUA
    - sudo cgcreate -t $(whoami):$(whoami) -a $(whoami):$(whoami) -g memory:tictactoe
