#!/bin/bash

set -ex

LUA=${LUA=lua}
P1=tictactoelib/examples/dumb_player.lua 

test1() {
    $LUA tictactoelib/run.lua $P1 $P1 | grep 'o won'
}

test2() {
    python3 -m unittest
}

test3() {
    # Install to virtualenv and run from cmdline
    python3 ./setup.py install
    tictactoelib $P1 $P1 | grep 'o won'
}

test1
test2
test3
