#!/bin/bash

set -ex

LUA=${LUA=lua}
P1=tictactoelib/examples/player1.lua 

test1() {
    $LUA tictactoelib/run.lua $P1 $P1 | grep 'o won'
}

test2() {
    python3 -m unittest
}

test3() {
    # Install to virtualenv and run from cmdline
    python3 ./setup.py install
    tictactoelib $P1 $P1 | grep 'o won'
}

test4() {
    # Install tictactoelib from pypi and test from cmdline
    VSN="`pip freeze | grep tictactoelib`"
    virtualenv -ppython3 env
    ./env/bin/pip install $VSN
    ./env/bin/tictactoelib $P1 $P1 | grep 'o won'
}

test1
test2
test3
test4
